ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inventory.urls',namespace ='inventory')),
    
    path('api/', include('inventory.urls',namespace ='inventory_api')),
    path('api-auth/', include('rest_framework.urls')),
    
    path("accounts/",include("account.urls",namespace='account')),
    path('main/', include('main.urls',namespace ='main')),
    
    
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/main/urls.py
from django.urls import path
from . import views



app_name='main'

urlpatterns = [
    # path('',views.now, name="block"),
    
    
    path('',views.MainView.as_view(), name="index"),
    path('register/',views.add_memoir, name="registermemoir"),
    # path('showuser/',views.ShowUserForBlockView.as_view(), name="showuser"),
    # path('block/',views.block, name="block"),
    # path('unblock/',views.unblock, name="unblock"),



]

ecommerce/templates/partials/footer.html
<div class="jumbotrom">

    <div class="containder">
        <hr>

       
        <h1 class= "text-center text-primary">  partials.footer.html-contact us:</h1>
    <h2>Phone number: +49 963 15 25 770*</h2>
    <h3>Address: Wetzlar, Hessen Hermansteinn, str .....</h3>
    <img src="{{media_url}}images/sliders/b.png" class="img-120" alt=".....">


    </div>


</div>

ecommerce/templates/partials/header.html
<div class="jumbotrom">

    <h1 class= "text-center text-info "> WELCOME ... Partials.header.html  </h1>



</div>

ecommerce/templates/partials/messages.html
{% if messages %}
{% for message in messages  %}
<h5 class="alert alert-{{message.tags}}">

    {{ message }}
</h5>

{% endfor %}
{% endif %}

ecommerce/templates/partials/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'inventory:index'%}"> Main Page  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


    <ul class="navbar-nav ">
        <li class="nav-item ">
          <a class="nav-link" href="{% url 'inventory:index' %}">Auto,Rad ,Boot</a>
        </li>
        
    </ul>

    <ul class="navbar-nav ">
      <li class="nav-item ">
        <a class="nav-link" href="{% url 'inventory:index' %}">House , Garden</a>
      </li>
      
  </ul>

  <ul class="navbar-nav ">
      <li class="nav-item ">
        <a class="nav-link" href="{% url 'inventory:index' %}">Mode , Beuty</a>
      </li>
      
  </ul>

  <ul class="navbar-nav ">
      <li class="nav-item ">
        <a class="nav-link" href="{% url 'inventory:index' %}">Jobs</a>
      </li>
      
  </ul>

  <ul class="navbar-nav ">
      <li class="nav-item ">
        <a class="nav-link" href="{% url 'inventory:index' %}">Music, Film , Bucher</a>
      </li>
      
  </ul>

  <ul class="navbar-nav ">
      <li class="nav-item ">
        <a class="nav-link" href="{% url 'inventory:index' %}">Freizeit , Hobby  and Nachbarschaft</a>
      </li>
      
  </ul>


  <ul class="navbar-nav ">
      <li class="nav-item ">
        <a class="nav-link" href="{% url 'inventory:index' %}">Dienstleistungen</a>
      </li>

  <ul class="navbar-nav ">
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'inventory:index' %}">Nachbarshaftshilfe</a>
      </li>
          
  </ul>


  <ul class="navbar-nav ">
      <li class="nav-item ">
        <a class="nav-link" href="{% url 'inventory:index' %}">Family , kind , baby</a>
      </li>
      
  </ul>
      
  </ul>













</nav>

ecommerce/templates/partials/slider.html
{% comment %}
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
        <div class="carousel-item active">
          <img class="d-block w-100" src="{{media_url}}/images/sliders/a.png" alt="First slide">
        </div>

        <div class="carousel-item">
          <img class="d-block w-100" src="{{media_url}}/images/sliders/b.png" alt="Second slide">
        </div>

        <div class="carousel-item">
          <img class="d-block w-100" src="{{media_url}}/images/sliders/c.png" alt="Second slide">
        </div>


  </div>
</div> {% endcomment %}




<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="media/images/sliders/a.png" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100"  src="media/images/sliders/b.png"  alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{{media_url}}/images/sliders/c.png"  alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
















{% comment %}
 <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" src="{{media_url}}/images/sliders/a.png" alt="First slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="{{media_url}}/images/sliders/b.png" alt="Second slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="{{media_url}}/images/sliders/c.png" alt="Second slide">
      </div>

    </div>
</div> {% endcomment %}