ecommerce/account/urls.py
from django.urls import path
from . import views

app_name='account'

urlpatterns = [
    path('register/',views.RegisterUserView.as_view(), name="register"),
    path('login/',views.LoginUserView.as_view(), name="login"),
    path('logout/',views.LogoutUserView.as_view(), name="logout"),


]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inventory.urls',namespace ='inventory')),
    
    path('api/', include('inventory.urls',namespace ='inventory_api')),
    path('api-auth/', include('rest_framework.urls')),
    
    path("accounts/",include("account.urls",namespace='account')),
    path('main/', include('main.urls',namespace ='main')),
    
    
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/main/urls.py
from django.urls import path
from . import views



app_name='main'

urlpatterns = [
    # path('',views.now, name="block"),
    
    
    path('',views.MainView.as_view(), name="index"),
    path('register/',views.add_memoir, name="registermemoir"),
    # path('showuser/',views.ShowUserForBlockView.as_view(), name="showuser"),
    # path('block/',views.block, name="block"),
    # path('unblock/',views.unblock, name="unblock"),



]

ecommerce/main/models.py
from django.db import models
from django.utils import timezone
# from account.models import User
from django.contrib.auth.models import User

# install crispy library helps to have text and images from 2 tables in one together
#pip install django-crispy-form: setting add INSTALLED_APPS:crispy_forms


# 1.Define our Memoir model:
class Memoir(models.Model):
    memoir_title = models.CharField(max_length=200, verbose_name='memoir title ')
    Memoir_text = models.TextField(verbose_name='memoir text ')
    register_data = models.DateTimeField(default=timezone.now)
    # the memoir is False first.Admin can True it to be visible .If it's not True don't show it .
    is_active = models.BooleanField(default=False)
    # null-True :means even the users without registeration can leave their memor
    user_registered = models.ForeignKey(User, on_delete = models.CASCADE,null=True)

    # returns a string (shows ) that is exactly rendered as the display name of instances for that model.
    def __str__(self): # in Terminal , Admin panel, shell ,
        return self.memoir_title





# 2.Define our Galley (images) Memoir model:
# for related_name , we should define a funcation to control in which the pic must be uploaded!
# instance of the memoirGallery
def upload_gallery_image(instance , filename):
    # return f"images/memoir/gallery/{filename}" works properly ! you can see the folder gallery created .
    # using instance we can  change our address following:
    return f"images/memoir/{instance.memoir.memoir_title}/gallery/{filename}"

class MemoirGallery(models.Model):

    Memoir_image_name = models.ImageField(upload_to=upload_gallery_image,verbose_name='memoir image ')
    #related_name = images  ,also added to Memoir as its field: Unknown field(s) (Memoir_image_name) specified for MemoirGallery
    # memoir code :using it we can connect this class to the Memoir !very CRUICIAL !!!
    # related :relation between one to N in  occurs in child
    # memoir code
    memoir=models.ForeignKey(Memoir, on_delete=models.CASCADE,null=True, related_name='images')





# To like a  Memoir we make  the following Model:
class MemoirLike(models.Model):
    # user liker code
    user_liked = models.ForeignKey(User,  on_delete = models.CASCADE,null=True)
    # memoir liked code
    memoir = models.ForeignKey(Memoir, on_delete=models.CASCADE,null=True)




# Admin can block a  User , could be from db or via Syntax
class UserBlocked(models.Model): # BlockedUSer
    # Using more than one foriegnKey use relatedname to avoid interference!
    user_blcoker =  models.ForeignKey(User, on_delete = models.CASCADE,null=True,related_name="blocker")
    user_blocked  = models.ForeignKey(User, on_delete = models.CASCADE,null=True,related_name="blocked")
    register_data = models.DateTimeField(default=timezone.now)

ecommerce/main/forms.py
from django import forms
from .models import Memoir , MemoirGallery

#Form for Memoir
class MemoirForm(forms.ModelForm):
    class Meta:
        model = Memoir
        fields = ['memoir_title','Memoir_text']




#Form for Gallery
class MemoirGalleryForm(forms.ModelForm):
    class Meta:
        model = MemoirGallery
        fields = ['Memoir_image_name']

ecommerce/main/views.py
from django.shortcuts import render , redirect
from django.views import View
from django.conf import settings
from django.forms import modelformset_factory
from account.models import CustomUser
from .models import MemoirGallery,Memoir,UserBlocked ,MemoirLike
from .forms import MemoirGalleryForm, MemoirForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin



# TEST template works or not 
from django.http import HttpResponse
# import datetime
# def now(request):
#     now = datetime.datetime.now() 
#     msg = f'Today is {now}'
#     return HttpResponse(msg, content_type='text/plain')

def media_admin(request):
    return {"media_url":settings.MEDIA_URL,}


class MainView(View):
    def get(self, request ,*args, **kwargs):
        memoi = Memoir.objects.all()
        #forms
        # form = MemoirForm
        # if request.method == 'GET':
        #     form = MemoirForm(request.GET)
        #     if form.is_valid():
        #         form.save()
        #         messages.success(request, 'Done','success')
        return render(request,'main_index.html',{ "memoi" : memoi})


    def post(self, request ,*args, **kwargs):
        pass
        
        # return render(request, 'templates/inventory_temp_app/index.html' , { "form" : form})




# 1.images and text of  Memoir:

# @login_required :unregistered USERs can not   surf our website pages & read memoirs
@login_required
def add_memoir(request):  
    ImageFormSet = modelformset_factory(MemoirGallery, form =MemoirGalleryForm, extra=4)
    if request.method =='GET':
        memoir_form = MemoirForm() # fields = ['memoir_title','Memoir_text']
        # in GET method ,we use none() means: DO NOT PUT ANYTHNG inside
        # A QuerySet is a collection of data from a database
        image_formset=ImageFormSet(queryset=MemoirGallery.objects.none(),)
        context={
            "memoir_form":memoir_form,
            "image_formset":image_formset
        }
        return render(request, 'register_memoir.html' ,context)
    elif request.method =='POST':
        memoir_form = MemoirForm(request.POST) #   title and text

        # request.FILES : get Both  text request.POST   and files request.FILES  from ImageFormSet
        image_formsset = ImageFormSet(request.POST,request.FILES)
        # TEST:
        # print(memoir_form.is_valid())
        # print(image_formset.is_valid())
        # print(100*'-')

        # To see the User  Added number in db :
        if memoir_form.is_valid() and image_formsset.is_valid(): # from valid (charfield , emailfield)
            # from main_memoir in db ,to obtain user_registered_id field
            cd = memoir_form.cleaned_data # a dictionary text & title  get from db as a dictionary
            mem_obj = Memoir.objects.create(
                memoir_title = cd["memoir_title"],
                Memoir_text = cd["Memoir_text"],
                user_registered = request.user # in veiw to access to user  request . user(from logged in USER)
            )


            # mem_obj = memoir_form.save() #memoir is saved
            for form in image_formsset.cleaned_data:
                if form: # if form had something with it
                    MemoirGallery.objects.create(
                        Memoir_image_name = form['Memoir_image_name'],
                        memoir= mem_obj
                    )
            messages.success(request, 'SAVED your Memoir  Successfully Done','success')
            return redirect('main:index')
        else:
            return render(request, 'register_memoir.html',{ "memoir_form":memoir_form })

ecommerce/main/templates/main_index.html
{% extends 'main_template.html' %}
<h1>hello  main.templates main.index main</h1>

{% block title %} You are selling... {% endblock title %}

{% block content %}
  {% include 'partials/slider.html' %}
   {% if user.is_authenticated %}
        <h1 class="text_center text-primary">Selling </h1>

        {% for memoir in memoirs %}
          <div class="card" >
            <div class="card-body">
                <h5 class="card-title">category</h5>
                <h5 class="card-title">{{ memoir.memoir_title }}</h5>

                <p class="card-text">
                {{ memoir.Memoir_text }}
                </p>
                {% for image in memoir.images.all %}
                {% comment %} <img class="card-img-top" src="{{media_url}}images/building.png" class='img-thumbnail img-120' alt=""> {% endcomment %}
                  {% comment %} <img src="{{media_url}}images/memoir/UA.png" class='img-thumbnail img-120' alt="..."> {% endcomment %}
                  <img src="{{media_url}}{{image.Memoir_image_name}}" class='img-thumbnail img-120' alt="...">
                {% endfor %}
                <div>
                {% if memoir.id  in list_liked_memoir_id %}
                <a href="#"> <i class= "fa fa-plus"></i></a>



                {% endif %}

            </div>
          </div>
    {% endfor %}
    {% else %}
      <h1 class="text_center text-info">Sorry , You should LOGIN to sell or buy  <a href="{% url 'account:login' %}">"Enter"</a> Here </h1>
 {% endif %}
{% endblock content %}

ecommerce/main/templates/register_memoir.html
<h1>hello main  templates  register_memoir</h1>
{% extends 'main_template.html' %}
{% load crispy_forms_tags %}

{% block title %} You are Selling  {% endblock title %}

{% block content %}
<h1 class= "text-center text-primary"> USER ENTERANCE</h1>
<div class="row justify-contentmd-center">
    <form action="" method="post" class="col-md-6 " enctype="multipart/form-data">
        {% csrf_token %}
        {{ memoir_form }}
       
        {% for form in  image_formset  %}
            {{ form  }}
        {% endfor %}


        <input type="submit" value="Register Memoir" class="btn btn-success btn-block">
    </form>
</div>

{% endblock content %}

ecommerce/main/templates/show_user.html
{% extends 'main_template.html' %}
<h1>main.templates show_user.html</h1>

{% extends 'main_template.html' %}
{% load crispy_forms_tags %}

{% block title %} writing memoir {% endblock title %}

{% block content %}
    {% for user  in users %}
        {% if user.id in blocked_list_id %}
            <a onclick="unblock({{user.id}})" id="btn_{{usr.id}}" href="#" class="btn btn-danger">{{user.name}} {{user.family}}</a>
        {% else %}
            <a onclick="block({{user.id}})" id="btn_{{usr.id}}" href="#" class="btn btn-primary">{{user.name}} {{user.family}}</a>
        {% endif %}

    {% endfor %}





<br>
 {% comment %} One method to show the id of  Blocked people in  {% endcomment %}
 {% for id  in blocked_list_id  %}
 <h3>This id number is  Blocked :</h3>
 <br>
         <h2>{{id}}</h2>
    {% endfor %}

{% endblock content %}